config/routes.rb
SampleApp::Application.routes.draw do
  get "users/new"

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',    :to => 'users#new'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110225194014
#
# Table name: users
#
#  id         :integer         not null, primary key
#  email      :string(255)
#  password   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :name, :email
  
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    # Return a title on a per-page basis.
    def title
      base_title = "Ruby on Rails Tutorial Sample App"
      if @title.nil?
        base_title
      else
        "#{base_title} | #{@title}"
      end
    end

  def logo
    image_tag("logo.png", :alt => "Sample App", :class => "round")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", signup_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js' %>
<%= javascript_include_tag 'rails' %>
<%= javascript_include_tag 'blueprint_showgrid.js' %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render :partial => 'layouts/stylesheets' %>
	<%= render :partial => 'layouts/javascripts' %>
  </head>

  <body>
    <div class="container">
      <%= render :partial => 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
	<%= render :partial => 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.haml
%h1 About Us
%p
 =link_to "Ruby on Rails Tutorial", "http://railstutorial.org/" 
 is a project to make a book and screencasts to teach web development with
 =link_to "Ruby on Rails", "http://rubyonrails.org/"
 %br
 
 This is the sample application for the tutorial.

app/views/pages/contact.html.haml
%h1 Contact
%p
 Contact Ruby on Rails Tutorial about the sample app at the
 =raw "#{link_to "feedback page", "http://railstutorial.org/feedback"}."

app/views/pages/help.html.haml
%h1 Help
<<<<<<< HEAD
%p
  Get help on Ruby on Rails Tutorial at the
  =link_to "Rails Tutorial help page", "http://railstutorial.org/help"
  %br
  To get help on this sample app, see the
  =link_to "Rails Tutorial book", "http://railstutorial.org/book"
=======

%p 
  Get help on Ruby on Rails Tutorial at the
  =raw "#{link_to "http://railstutorial.org/help", "Rails Tutorial help page"}."
  %br
 	
  To get help on this sample app, see the
  =raw "#{link_to "http://railstutorial.org/book", "Rails Tutorial book"}."
>>>>>>> 415e9b61b634e303c2296251991a4a71492f8b5c

app/views/pages/home.html.haml
%h1 Sample App

%p
 This is the home page for the
 =link_to "Ruby on Rails Tutorial", "http://railstutorial.org/"
 sample application.

=link_to "Sign up now!", signup_path, :class => "signup_button round"

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.haml
%h1 Users#new

%p Find me in app/views/users/new.html.erb